
version: '2'

services:
  skillbased-api:
    container_name: skillbased-api
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
    - "127.0.0.1:8080:8080"
    environment:
      PG_HOST: "localhost"
      PG_PORT: 5432
      PG_USER: "user"
      PG_PASSWORD: "ball"
      PG_DATABASE: "skillbased"


  postgres:
    restart: always
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ball
      POSTGRES_DB: vpnaas
